# Generated by Django 5.1.4 on 2024-12-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_pasta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.AddField(
            model_name='projeto',
            name='idProjeto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='nomeProjeto',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
